version: 0.0
os: linux
files:
  - source: /
    destination: /home/sigmoid/Nancy/node-docker/node-docker
permissions:
  - object: /home/sigmoid/Nancy/node-docker/node-docker
    pattern: "**"
    group: apache
    mode: 755
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
