version: 0.2

env:
  variables:
    DOCKER_USERNAME: "nancysinghal"
    DOCKER_PASSWORD: "Nancy@100"
    DOCKER_IMAGE_NAME: "nancysinghal/node-docker-app"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install

  pre_build:
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - docker build -t $DOCKER_IMAGE_NAME .

  post_build:
    commands:
      - docker push $DOCKER_IMAGE_NAME

artifacts:
  files: Dockerfile