version: 0.2

env:
  variables:
    DOCKER_USERNAME: "nancysinghal"
    DOCKER_PASSWORD: "Nancy@100"
    DOCKER_IMAGE_NAME: "nancysinghal/node-docker-app"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
      - apt-get update -y
      - apt-get install -y docker.io

  pre_build:
    commands:
      - aws --version
      - aws configure list
      - sudo chmod 666 /var/run/docker.sock
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo Building Docker image...
      - docker -v
      - docker build -t $DOCKER_IMAGE_NAME .

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push $DOCKER_IMAGE_NAME

artifacts:
  files: Dockerfile

privilege-mode: true